### ISSUE TITLE
strange behavior can't build  nativescript-socket.io

### ISSUE THREAD

**Issue by gezn** [naderio/nativescript-socket.io#49]
when running tns run android. this happens:

Unable to apply changes on device: 192.168.56.101:5555. Error is: Failed to build plugin nativescript-socket.io : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/pedroteran/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
.

node version 7.7.4.
npm version 4.1.2

doess anyone knows why this could happen?

**Comment by jaasaria** [comment]
any clear solution for this? everytime there's an update in my gradle i receive this error. takes so much time to uninstall / install files.

work around:
1.
delete folder: \platform
wipe data in my emulator using android studio
restart pc and run 

2.
removing ns-socket.io and devtools (for the meantime)
	- removing devtools (main.js)

**Comment by gezn** [comment]
I fixed this and the strange behaviour with the library by moving to the latests node lts 8.12.0
maybe this could help you

**Comment by r0nneberg** [comment]
unfortunately the fix didn't worked for me. still have this issue
